import "./globals.css";
import { Inter } from "next/font/google";
import { AppProps } from "next/app";
import { GlobalDataProvider } from "@/hooks/useGlobalData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalDataProvider>{children}</GlobalDataProvider>
      </body>
    </html>
  );
}
